In [1]:
import numpy as np

arr = np.arange(1,21)
print(arr)
print("The shape of array is:", arr.shape)
print("The minimum value in array is:", min(arr))
print("The Maximum value in atrray is:" ,max(arr))
mean = np.mean(arr)
print("The mean of the array is:" , mean)
stand = np.std(arr)
print("The standard deviation of the array is:", stand)
arr_1 = arr.reshape(4,5)
print("the new shape of array is:\n", arr_1)
print("the second row of new shaped array is:")
for i in range(0,5):
    print(arr_1[1][i], end = " ")
print("\nthe third column of new shaped array is:")
for j in range(0,4):
    print(arr_1[j][2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The shape of array is: (20,)
The minimum value in array is: 1
The Maximum value in atrray is: 20
The mean of the array is: 10.5
The standard deviation of the array is: 5.766281297335398
the new shape of array is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
the second row of new shaped array is:
6 7 8 9 10
the third column of new shaped array is:
3
8
13
18

In [2]:
import numpy as np
A = np.array([10,20,30,40,50])
B = np.array([5,10,15,20,25])
addn = [x + y for x,y in zip(A,B)]
print("The sum of both sets:", addn)
subt = [y - x for y,x in zip(B,A)]
print("Subtraction from b to a:" , subt)
mult = [x*y for x,y in zip(A,B)]
print("Multiplication:", mult)
div = [x/y for x,y in zip(A,B)]
print("Division:", div)
sum = 0
for i in range(0,4):
    sum += A[i]
print("The total sum of A:" , sum)

The sum of both sets: [np.int64(15), np.int64(30), np.int64(45), np.int64(60), np.int64(75)]
Subtraction from b to a: [np.int64(-5), np.int64(-10), np.int64(-15), np.int64(-20), np.int64(-25)]
Multiplication: [np.int64(50), np.int64(200), np.int64(450), np.int64(800), np.int64(1250)]
Division: [np.float64(2.0), np.float64(2.0), np.float64(2.0), np.float64(2.0), np.float64(2.0)]
The total sum of A: 100

In [3]:
import numpy as np
import pandas as pd

data = {"Roll No" : [101,102,103,104,105],
        "Name" : ["Ravi", "Priya" , "Kiran", "Anu", "Sita"],
        "Marks" : [85,92,78,88,95]}
df = pd.DataFrame(data)
display(df)
display("First three records:", df[0:3])
print("the average marks:", df['Marks'].mean())
print("The person with highest marks:", df.loc[df['Marks'].idxmax(), 'Name'])
print("The person with the lowest marks:", df.loc[df['Marks'].idxmin(), 'Name'])
df['Grade'] = ['B','A','C','B','A']
display(df)

   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95

'First three records:'

   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78

the average marks: 87.6
The person with highest marks: Sita
The person with the lowest marks: Kiran

   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A

In [4]:
import numpy as np
import pandas as pd

data = {'Product' : ['Laptop','Mouse','Keyboard','Monitor'],
        'Price' : [50000,500,1200,10000],
        'Quantity' : [10,50,30,15]}
df = pd.DataFrame(data)
display(df)
df['Total Value'] = df['Price'] * df['Quantity']
display(df)
high = df.loc[df['Total Value'].idxmax(),'Product']
print("The highest total value product is:",high)

total = (df['Total Value']).sum()
print("The total inventory value is:",total)

    Product  Price  Quantity
0    Laptop  50000        10
1     Mouse    500        50
2  Keyboard   1200        30
3   Monitor  10000        15

    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

The highest total value product is: Laptop
The total inventory value is: 711000

In [2]:
import pandas as pd

df = pd.read_csv("iris.csv")
display(df)
display("The First 5 Rows:",df[0:4])
display("The shape of the dataset:",df.shape)
display("Columns names:",df.columns)
display("Summary of the Statistics:" ,df.describe())
display("Missing Values Summary:",df.isna().sum())
display("The Sample Values:", df['virginica'].value_counts())

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

'The First 5 Rows:'

   150    4  setosa  versicolor  virginica
0  5.1  3.5     1.4         0.2          0
1  4.9  3.0     1.4         0.2          0
2  4.7  3.2     1.3         0.2          0
3  4.6  3.1     1.5         0.2          0

'The shape of the dataset:'

(150, 5)

'Columns names:'

Index(['150', '4', 'setosa', 'versicolor', 'virginica'], dtype='str')

'Summary of the Statistics:'

              150           4      setosa  versicolor   virginica
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

'Missing Values Summary:'

150           0
4             0
setosa        0
versicolor    0
virginica     0
dtype: int64

'The Sample Values:'

virginica
0    50
1    50
2    50
Name: count, dtype: int64